export const SET_CONTENTS = 'SET_CONTENTS';
export const SET_COMMON_SIDEBAR = 'SET_COMMON_SIDEBAR';
export const SET_COMMON_IS_ACTIVE_SIDEBAR = 'SET_COMMON_IS_ACTIVE_SIDEBAR';

/* Furnitures */
export const SET_FURNITURES = 'SET_FURNITURES';
export const SET_IS_CHANGE_FURNITURE = 'SET_IS_CHANGE_FURNITURE';
export const SET_FURNITURE_DETAIL = 'SET_FURNITURE_DETAIL';

/* Buildings */
export const SET_BUILDINGS = 'SET_BUILDINGS';
export const SET_BUILDING_DETAIL = 'SET_BUILDING_DETAIL';

/* Areas */
export const SET_IS_CHANGE_AREA = 'SET_IS_CHANGE_AREA';
export const SET_AREAS = 'SET_AREAS';
export const SET_AREA_DETAIL = 'SET_AREA_DETAIL';
